# Generated by Django 5.2.8 on 2025-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('protocol_type', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], max_length=10)),
                ('service', models.CharField(max_length=50)),
                ('src_bytes', models.IntegerField()),
                ('dst_bytes', models.IntegerField()),
                ('flag', models.CharField(choices=[('SF', 'SF'), ('S0', 'S0'), ('REJ', 'REJ'), ('RSTR', 'RSTR'), ('RSTO', 'RSTO'), ('SH', 'SH'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('OTH', 'OTH'), ('RSTOS0', 'RSTOS0')], max_length=10)),
                ('wrong_fragment', models.IntegerField()),
                ('urgent', models.IntegerField()),
                ('count', models.IntegerField()),
                ('serror_rate', models.FloatField(blank=True, null=True)),
                ('rerror_rate', models.FloatField(blank=True, null=True)),
                ('same_srv_rate', models.FloatField(blank=True, null=True)),
                ('diff_srv_rate', models.FloatField(blank=True, null=True)),
                ('srv_count', models.IntegerField()),
                ('srv_serror_rate', models.FloatField(blank=True, null=True)),
                ('srv_rerror_rate', models.FloatField(blank=True, null=True)),
                ('srv_diff_host_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_count', models.IntegerField()),
                ('dst_host_srv_count', models.IntegerField()),
                ('dst_host_same_srv_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_diff_srv_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_same_src_port_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_srv_diff_host_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_serror_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_srv_serror_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_rerror_rate', models.FloatField(blank=True, null=True)),
                ('dst_host_srv_rerror_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
