from django import forms

class NidsForm(forms.Form):
    Duration = forms.FloatField()
    Protocol_type = forms.CharField()
    Service = forms.CharField()
    Src_bytes = forms.FloatField()
    Dst_bytes = forms.FloatField()
    Flag = forms.CharField()
    Land = forms.IntegerField()
    Wrong_fragment = forms.FloatField()
    Urgent = forms.FloatField()

    Hot = forms.FloatField()
    Num_failed_logins = forms.FloatField()
    Logged_in = forms.FloatField()
    Root_shell = forms.FloatField()
    Su_attempted = forms.FloatField()
    Num_root = forms.FloatField()
    Num_file_creations = forms.FloatField()
    Num_shells = forms.FloatField()
    Num_access_files = forms.FloatField()
    Num_outbound_cmds = forms.FloatField()
    Is_hot_login = forms.FloatField()
    Is_guest_login = forms.FloatField()
    Count = forms.FloatField()
    Serror_rate = forms.FloatField()
    Rerror_rate = forms.FloatField()
    Same_srv_rate = forms.FloatField()
    Diff_srv_rate = forms.FloatField()
    Srv_count = forms.FloatField()
    Srv_serror_rate = forms.FloatField()
    Srv_rerror_rate = forms.FloatField()
    Srv_diff_host_rate = forms.FloatField()
